# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/project_1/project_1.cache/wt [current_project]
set_property parent.project_path D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/defines.h
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/TOP/config.h
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/utility.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/APB_DEV/URT/uart_defines.h
}
set_property file_type "Verilog Header" [get_files D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/defines.h]
set_property file_type "Verilog Header" [get_files D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/TOP/config.h]
set_property file_type "Verilog Header" [get_files D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/utility.v]
set_property file_type "Verilog Header" [get_files D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/APB_DEV/URT/uart_defines.h]
read_verilog -library xil_defaultlib {
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/LLbit_reg.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/TLB.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/adder.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/alu.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/aludec.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/APB_DEV/apb_dev_top.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/APB_DEV/apb_mux2.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/AMBA/axi2apb.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/axi_interface.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/AMBA/axi_mux.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/bd.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/CONFREG/confreg.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/controller.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/cp0.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/csr.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/d_cache.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/d_confreg_port.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/datapath.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/divider_Primary.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/DMA/dma.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/dma.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/eqcmp.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/ethernet_top.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/exception.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/flopenrc.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/floprc.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/SPI/godson_sbridge_spi.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/hazard.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/hilo_reg.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/i_cache.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/instdec.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/mac.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/mac2axi.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/mac_axi.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/mac_top.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/maccsr2axi.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/macdata2axi.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/maindec.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/memsel.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/mips.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/mux2.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/mux3.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/mux4.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/APB_DEV/NAND/nand.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/APB_DEV/nand_module.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/pc.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/APB_DEV/URT/raminfr.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/rc.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/regfile.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/rfifo.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/rlsm.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/rstc.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/signext.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/cpu232/sl2.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/tc.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/tfifo.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/MAC/tlsm.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/APB_DEV/URT/uart_receiver.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/APB_DEV/URT/uart_regs.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/APB_DEV/URT/uart_rfifo.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/APB_DEV/URT/uart_sync_flops.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/APB_DEV/URT/uart_tfifo.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/APB_DEV/URT/uart_top.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/APB_DEV/URT/uart_transmitter.v
  D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/rtl/TOP/soc_up_top.v
}
read_ip -quiet D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/dpram_512x32/dpram_512x32.xci
set_property used_in_implementation false [get_files -all d:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/dpram_512x32/dpram_512x32_ooc.xdc]

read_ip -quiet D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33.xci
set_property used_in_implementation false [get_files -all d:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33_board.xdc]
set_property used_in_implementation false [get_files -all d:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33.xdc]
set_property used_in_implementation false [get_files -all d:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33_late.xdc]
set_property used_in_implementation false [get_files -all d:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33_ooc.xdc]

read_ip -quiet D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/clk_wiz_0/clk_wiz_0_late.xdc]
set_property used_in_implementation false [get_files -all d:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/axi_interconnect_0/axi_interconnect_0.xci
set_property used_in_synthesis false [get_files -all d:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/axi_interconnect_0/axi_interconnect_0_impl_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/axi_interconnect_0/axi_interconnect_0_impl_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/axi_interconnect_0/axi_interconnect_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/axi_interconnect_0/axi_interconnect_0_clocks.xdc]

read_ip -quiet D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/mig_axi_32/mig_axi_32.xci
set_property used_in_implementation false [get_files -all d:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/mig_axi_32/mig_axi_32/user_design/constraints/mig_axi_32.xdc]
set_property used_in_implementation false [get_files -all d:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/project_1/xilinx_ip/mig_axi_32/mig_axi_32/user_design/constraints/mig_axi_32_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/soc_up.xdc
set_property used_in_implementation false [get_files D:/PUA_CPU/nscscc2023-group-mips/soc_run_os_v0.01/soc_up/vivado_xpr/soc_up.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_up_top -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_up_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_up_top_utilization_synth.rpt -pb soc_up_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
